[tox]
envlist = py39

[testenv]
usedevelop = True
passenv = *
deps = 
    -r./requirements.txt
    pytest>=7.0.0
    pytest-cov>=4.0.0
    pytest-env>=1.0.0
    coverage>=7.0.0
    pydocstyle>=6.0.0
    pylint>=2.0.0
basepython = python3.9
commands =
    pytest {env:TOX_PYTEST_ARGS:-vv -s --cov=register_apps --cov-report=term-missing tests}
    pylint register_apps --rcfile={toxinidir}/.pylintrc || true
    pydocstyle register_apps --config={toxinidir}/.pydocstylerc || true
