[tox]
envlist = py39

[testenv]
usedevelop = True
passenv = *
deps = 
    -r./requirements.txt
basepython = python3.9
commands =
    pytest {env:TOX_PYTEST_ARGS:-vv -s --cov=register_apps --cov-report=term-missing tests}
    pylint register_apps --rcfile={toxinidir}/.pylintrc || true
    pydocstyle register_apps --config={toxinidir}/.pydocstylerc || true
